create database BANK030;
USE BANK030;

create table BRANCH(
	BRANCH_NAME VARCHAR(45),
    BRANCH_CITY VARCHAR(45), 
    ASSESTS REAL,
    PRIMARY KEY(BRANCH_NAME)
    );
create table ACCOUNTS(
	ACCNO INT, 
    BRANCH_NAME VARCHAR(45),
    BALANCE REAL,
    PRIMARY KEY(ACCNO),
    FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME)
    );
create table CUSTOMER(
	CUSTOMER_NAME VARCHAR(45), 
    CUSTOMER_STREET VARCHAR(45), 
    CUSTOMER_CITY VARCHAR(45),
    PRIMARY KEY(CUSTOMER_NAME)
    );
create table DEPOSITOR(
	CUSTOMER_NAME VARCHAR(45),
    ACCNO INT,
    PRIMARY KEY(CUSTOMER_NAME,ACCNO),
    FOREIGN KEY(CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME),
    FOREIGN KEY(ACCNO) REFERENCES ACCOUNTS(ACCNO)
    );
create table LOAN(
	LOAN_NUMBER INT, 
    BRANCH_NAME VARCHAR(45), 
    AMOUNT REAL,
    PRIMARY KEY(LOAN_NUMBER),
    FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME)
    );
create table BORROWER(
	CUSTOMER_NAME VARCHAR(45),
    LOAN_NUMBER INT,
    PRIMARY KEY(CUSTOMER_NAME, LOAN_NUMBER),
    FOREIGN KEY (CUSTOMER_NAME) REFERENCES CUSTOMER(CUSTOMER_NAME),
    FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER)
    );
    
INSERT INTO BRANCH(BRANCH_NAME, BRANCH_CITY, ASSESTS) VALUES
	('SBI_Chamrajpet','Bangalore',50000),
    ('SBI_ResidencyRoad', 'Bangalore',10000),
    ('SBI Shivaji Road', 'Bombay', 20000),
    ('SBI_ParlimentRoad', 'Delhi',10000),
	('SBI_Jantarmantar', 'Delhi', 20000);
SELECT * FROM BRANCH;
commit;
INSERT INTO ACCOUNTS(ACCNO, BRANCH_NAME,BALANCE) VALUES 
	(
