create database BANK;
USE BANK;

create table BRANCH(BRANCH_NAME VARCHAR(45), BRANCH_CITY VARCHAR(45), ASSESTS REAL);
DESC BRANCH;
create table ACCOUNTS(ACCNO INT, BRANCH_NAME VARCHAR(45), BALANCE REAL);
DESC ACCOUNTS;
create table DEPOSITOR(CUSTOMER_NAME VARCHAR(45), CUSTOMER_STREET VARCHAR(45), CUSTOMER_CITY VARCHAR(45));
DESC DEPOSITOR;
create table LOAN(LOAN_NUMBER INT, BRANCH_NAME VARCHAR(45), AMOUNT REAL);
DESC LOAN;
create table BORROWER(CUSTOMER_NAME VARCHAR(45), LOAN_NUMBER INT);

ALTER TABLE BRANCH ADD PRIMARY KEY(BRANCH_NAME);
ALTER TABLE ACCOUNTS ADD PRIMARY KEY(ACCNO);
ALTER TABLE ACCOUNTS ADD FOREIGN KEY (BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME);
ALTER TABLE DEPOSITOR ADD PRIMARY KEY(CUSTOMER_NAME);
ALTER TABLE LOAN ADD PRIMARY KEY(LOAN_NUMBER);
ALTER TABLE LOAN ADD FOREIGN KEY(BRANCH_NAME) REFERENCES BRANCH(BRANCH_NAME);
ALTER TABLE BORROWER ADD PRIMARY KEY(CUSTOMER_NAME, LOAN_NUMBER);
ALTER TABLE BORROWER ADD FOREIGN KEY(CUSTOMER_NAME) REFERENCES DEPOSITOR(CUSTOMER_NAME);
ALTER TABLE BORROWER ADD FOREIGN KEY(LOAN_NUMBER) REFERENCES LOAN(LOAN_NUMBER);
